/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: { extend: {} },
  plugins: [],
  safelist: [
    // colors
    'color-yellow-400',
    'color-green-400',
    'color-blue-400',
    // font-size
    'text-xs',
    'text-sm',
    'text-md',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'text-7xl',
    'text-8xl',
    'text-9xl',
    // padding-top
    'pt-0',
    'pt-px',
    'pt-0.5',
    'pt-1',
    'pt-1.5',
    'pt-2',
    'pt-2.5',
    'pt-3',
    'pt-3.5',
    'pt-4',
    'pt-5',
    'pt-6',
    'pt-7',
    'pt-8',
    'pt-9',
    'pt-10',
    'pt-11',
    'pt-12',
    'pt-14',
    'pt-16',
    'pt-20',
    'pt-24',
    'pt-28',
    'pt-32',
    'pt-36',
    'pt-40',
    'pt-44',
    'pt-48',
    'pt-52',
    'pt-56',
    'pt-60',
    'pt-64',
    'pt-72',
    'pt-80',
    'pt-96',
    // order
    'sm:order-1',
    'sm:order-2',
    'sm:order-3',
  ],
};
